(()=>{
'use strict';
const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
const imp=item=>item?.importance||'medium';
const importanceLabel={low:'一般',medium:'重要',high:'关键',urgent:'冲刺'};
function ensureRollup(level,date,subject,kind='总结'){
 const key=`${level}|${date}|${subject}|auto-${kind}`;
 let node=state.plans.find(p=>p.autoSummary&&p.summaryKey===key);
 if(!node){node={id:uid('plan'),level,date,time:'AUTO',title:`${kind} · ${subject}`,subject,minutes:0,importance:'medium',done:false,moved:false,autoSummary:true,summaryKey:key,progress:0};state.plans.push(node)}
 return node;
}
function syncLongTerm(opts,count){const level=opts.level||state.activePlanLevel;if(level!=='day')return;const baseDate=opts.date||state.planAnchor,start=new Date(baseDate+'T12:00:00'),week=dateKey(startOfWeek(start)),month=baseDate.slice(0,7),year=baseDate.slice(0,4),subject=opts.subject||'其他';ensureRollup('week',week,subject,'任务总结');ensureRollup('month',month,subject,'月度总结');ensureRollup('year',year,subject,'年度总结')}
function syncCountdownMilestones(){for(const c of state.countdowns||[]){if(!c.date)continue;const year=String(new Date(c.date).getFullYear()),key='countdown:'+c.id;let node=state.plans.find(p=>p.sourceKey===key);if(!node){state.plans.push({id:uid('plan'),level:'year',date:year,time:'节点',title:'重要节点 · '+c.name,subject:'综合',minutes:0,importance:c.importance||'high',done:false,moved:false,sourceKey:key,countdownDate:c.date});}}}
const oldAddPlanBatch=addPlanBatch;
addPlanBatch=function(opts){const result=oldAddPlanBatch(opts);syncLongTerm(opts,result);return result};
const oldSavePlanItems=savePlanItems;
savePlanItems=function(opts){const result=oldSavePlanItems(opts);syncLongTerm(opts,result);save(true);return result};
const oldAddSession=addSession;
addSession=function(subject,minutes,content){state.reports=state.reports||{};delete state.reports[today()];oldAddSession(subject,minutes,content);renderPlan();renderDashboard();renderLog();};
function planNodeHtml(p,small=false){const cls=`plan-node importance-${imp(p)} ${p.done?'done':''} ${small?'small':''}`;return `<button class="${cls}" data-plan-edit="${p.id}"><span>${esc(p.title)}</span><small>${esc(p.subject)}${p.progress!=null?' · '+p.progress+'%':''}</small></button>`}
function renderYearSpecial(){const year=String(new Date(state.planAnchor+'T12:00:00').getFullYear()),months=Array.from({length:12},(_,i)=>`${year}-${pad(i+1)}`),yearNodes=state.plans.filter(p=>p.level==='year'&&String(p.date).startsWith(year)),subjects=[...new Set([...state.target.subjects.map(s=>s.name),...months.flatMap(m=>state.plans.filter(p=>p.level==='month'&&p.date===m).map(p=>p.subject))])];const colors=['#ff8eae','#6eb9ff','#57d3b4','#9485ff','#ffd45c'];const calendar=months.map((month,i)=>{const nodes=[...state.plans.filter(p=>p.level==='month'&&p.date===month),...state.countdowns.filter(c=>(c.date||'').startsWith(month)).map(c=>({id:'cd-'+c.id,level:'year',date:year,title:c.name,subject:'综合',importance:c.importance||'high',countdownDate:c.date}))];return `<div class="year-month-card"><button class="month-add" data-add-plan-node="month" data-node-date="${month}-01">＋</button><strong>${i+1}月</strong><div>${nodes.slice(0,5).map(n=>n.id.startsWith('cd-')?`<span class="year-node importance-${imp(n)}">📌 ${esc(n.title)}</span>`:planNodeHtml(n,true)).join('')||'<small class="muted-text">暂无节点</small>'}</div></div>`}).join('');const monthDays=Array.from({length:12},(_,i)=>new Date(Number(year),i+1,0).getDate());const gantt=subjects.map((subject,row)=>{const bars=months.map((m,i)=>{const plans=state.plans.filter(p=>p.subject===subject&&((p.level==='month'&&p.date===m)||(p.level==='year'&&String(p.date)===year))),count=plans.length;return count?`<i style="grid-column:${i+1};background:${colors[row%colors.length]}" title="${subject} · ${i+1}月 · ${count}项">${count}</i>`:''}).join('');return `<div class="gantt-row"><b>${esc(subject)}</b><div class="gantt-track">${bars}</div></div>`}).join('');q('#planBoard').innerHTML=`<div class="year-planner"><div class="year-section-head"><div><h3>12 宫格年历</h3><p>月份、年度任务和倒计时重要节点放在同一张图里。</p></div><button class="soft-button small" data-add-plan-node="year" data-node-date="${year}-01-01">＋ 年度节点</button></div><div class="year-calendar">${calendar}</div><div class="year-section-head"><div><h3>学科甘特图</h3><p>不同颜色代表不同学科，颜色深浅对应重要性。</p></div></div><div class="gantt-chart"><div class="gantt-months">${months.map(m=>`<span>${Number(m.slice(-2))}月</span>`).join('')}</div>${gantt||'<p class="muted-text">添加月计划后生成甘特图</p>'}</div><div class="year-priority-list">${yearNodes.map(n=>planNodeHtml(n)).join('')}</div></div>`}
function renderMonthSpecial(){const anchor=new Date(state.planAnchor+'T12:00:00'),year=anchor.getFullYear(),month=anchor.getMonth(),first=new Date(year,month,1),offset=(first.getDay()+6)%7,days=new Date(year,month+1,0).getDate(),monthKey=`${year}-${pad(month+1)}`;let cells='';for(let i=0;i<offset;i++)cells+='<span class="month-day empty"></span>';for(let d=1;d<=days;d++){const key=`${monthKey}-${pad(d)}`,items=state.plans.filter(p=>p.level==='day'&&p.date===key),milestones=(state.countdowns||[]).filter(c=>(c.date||'').startsWith(key));cells+=`<div class="month-day ${key===today()?'today':''}"><button data-add-plan-node="day" data-node-date="${key}">${d}</button>${items.slice(0,3).map(p=>planNodeHtml(p,true)).join('')}${milestones.map(c=>`<span class="year-node importance-${imp(c)}">📌 ${esc(c.name)}</span>`).join('')}</div>`}const pool=state.plans.filter(p=>p.level==='month'&&p.date===monthKey);q('#planBoard').innerHTML=`<div class="month-planner"><div class="month-calendar-head"><span>一</span><span>二</span><span>三</span><span>四</span><span>五</span><span>六</span><span>日</span></div><div class="month-calendar">${cells}</div><div class="month-task-pool"><div class="year-section-head"><div><h3>任务池</h3><p>本月可自由分配的学习内容</p></div><button class="soft-button small" data-add-plan-node="month" data-node-date="${monthKey}-01">＋ 添加节点</button></div><div>${pool.map(p=>planNodeHtml(p)).join('')||'<p class="muted-text">暂无月度任务</p>'}</div></div></div>`}
function renderWeekSpecial(){const start=startOfWeek(new Date(state.planAnchor+'T12:00:00')),days=Array.from({length:7},(_,i)=>addDays(start,i)),subjects=state.target.subjects.map(s=>s.name);q('#planBoard').innerHTML=`<div class="week-board">${days.map((d,i)=>{const key=dateKey(d),items=state.plans.filter(p=>p.level==='day'&&p.date===key),weekNodes=state.plans.filter(p=>p.level==='week'&&p.date===key&&p.autoSummary);return `<div class="week-column ${key===today()?'today':''}"><div class="week-column-head"><span>周${['一','二','三','四','五','六','日'][i]}</span><b>${d.getMonth()+1}/${d.getDate()}</b><button data-add-plan-node="day" data-node-date="${key}">＋</button></div>${weekNodes.map(p=>planNodeHtml(p,true)).join('')}${items.map(p=>planNodeHtml(p)).join('')}${!items.length&&!weekNodes.length?'<small class="muted-text">暂无安排</small>':''}</div>`}).join('')}</div><div class="week-subject-legend">${subjects.map((s,i)=>`<span><i style="background:${['#ff8eae','#6eb9ff','#57d3b4','#9485ff'][i%4]}"></i>${esc(s)}</span>`).join('')}</div>`}
function refreshRollupProgress(){for(const node of state.plans.filter(p=>p.autoSummary)){const [level,date,subject]=String(node.summaryKey||'').split('|'),items=state.plans.filter(p=>p.level==='day'&&p.subject===subject&&(level==='week'?dateKey(startOfWeek(new Date(p.date+'T12:00:00')))===date:level==='month'?p.date.startsWith(date):p.date.startsWith(date)));node.progress=items.length?Math.round(items.filter(p=>p.done).length/items.length*100):0}}
const baseRenderPlan=renderPlan;
renderPlan=function(){syncCountdownMilestones();refreshRollupProgress();baseRenderPlan();if(state.activePlanLevel==='year')renderYearSpecial();else if(state.activePlanLevel==='month')renderMonthSpecial();else if(state.activePlanLevel==='week')renderWeekSpecial()};
function ensureNodeDialog(){if(q('#planNodeDialog'))return;document.body.insertAdjacentHTML('beforeend',`<dialog class="modal" id="planNodeDialog"><form method="dialog"><div class="modal-head"><div><span class="eyebrow">PLAN NODE</span><h2>编辑计划节点</h2></div><button class="modal-close" type="button" data-dialog-exit>退出 ×</button></div><label><span>节点名称</span><input id="nodeTitleInput" required maxlength="50" /></label><div class="form-grid two"><label><span>层级</span><select id="nodeLevelInput"><option value="year">年计划</option><option value="month">月计划</option><option value="week">周计划</option><option value="day">日计划</option></select></label><label><span>重要性</span><select id="nodeImportanceInput"><option value="low">一般</option><option value="medium">重要</option><option value="high">关键</option><option value="urgent">冲刺节点</option></select></label></div><div class="form-grid two"><label><span>科目</span><select id="nodeSubjectInput"><option>数学</option><option>英语</option><option>政治</option><option>专业课</option><option>综合</option></select></label><label><span>日期</span><input type="date" id="nodeDateInput" /></label></div><div class="form-grid two"><label><span>时间</span><input id="nodeTimeInput" maxlength="20" value="09:00" /></label><label><span>预计分钟</span><input type="number" id="nodeMinutesInput" min="0" max="600" value="60" /></label></div><input type="hidden" id="nodeIdInput" /><div class="modal-actions"><button class="soft-button" type="button" data-dialog-exit>退出</button><button class="primary-button" type="button" id="savePlanNodeBtn">保存节点</button></div></form></dialog>`)}
function openPlanNode(level='day',date='',id=''){ensureNodeDialog();const p=id?state.plans.find(x=>x.id===id):null;q('#nodeTitleInput').value=p?.title||'';q('#nodeLevelInput').value=p?.level||level;q('#nodeImportanceInput').value=p?.importance||'medium';q('#nodeSubjectInput').value=p?.subject||'数学';q('#nodeDateInput').value=p?.date?.length===10?p.date:date||today();q('#nodeTimeInput').value=p?.time||'09:00';q('#nodeMinutesInput').value=p?.minutes||60;q('#nodeIdInput').value=p?.id||'';q('#planNodeDialog').showModal()}
function savePlanNode(){const id=q('#nodeIdInput').value,level=q('#nodeLevelInput').value,date=q('#nodeDateInput').value,data={title:q('#nodeTitleInput').value.trim(),level,importance:q('#nodeImportanceInput').value,subject:q('#nodeSubjectInput').value,date:level==='year'?date.slice(0,4):level==='month'?date.slice(0,7):level==='week'?dateKey(startOfWeek(new Date(date+'T12:00:00'))):date,time:q('#nodeTimeInput').value||'09:00',minutes:+q('#nodeMinutesInput').value||0};if(!data.title){toast('请输入节点名称','warn');return}if(id){Object.assign(state.plans.find(x=>x.id===id),data)}else state.plans.push({id:uid('plan'),...data,done:false,moved:false});state.reports=state.reports||{};delete state.reports[today()];save(true);q('#planNodeDialog').close();renderPlan();renderHome();renderDashboard();toast('计划节点已保存','success')}
function renderMockTests(){const tests=state.mockTests||[];q('#mockTestGrid').innerHTML=state.target.subjects.map(s=>{const rows=tests.filter(t=>t.subject===s.name).sort((a,b)=>a.date.localeCompare(b.date)),latest=rows[rows.length-1],best=rows.length?Math.max(...rows.map(t=>Math.round(t.score/t.fullScore*100))):0;return `<div class="mock-subject-card"><header><span>${esc(s.name)}</span><small>满分 ${s.name==='数学'||s.name==='专业课'?'150':'100'}</small></header><strong>${latest?latest.score:'—'}</strong><small>${latest?latest.date+' · '+Math.round(latest.score/latest.fullScore*100)+'%':'还没有测试记录'}</small><div class="mock-test-history">${rows.slice(-3).reverse().map(t=>`<span>${t.date} · ${t.score}/${t.fullScore}${t.note?' · '+esc(t.note):''}</span>`).join('')}</div><small>历史最佳 ${best||0}%</small></div>`}).join('')}
const baseGenerateReport=generateLearningReport;
generateLearningReport=function(){const tests=(state.mockTests||[]).slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4);return baseGenerateReport()+'\n\n模拟测试：'+(tests.length?tests.map(t=>`${t.subject} ${t.score}/${t.fullScore}`).join('；'):'暂无记录')};
const baseRenderDashboard=renderDashboard;
renderDashboard=function(){state.mockTests=state.mockTests||[];baseRenderDashboard();renderMockTests()};
const baseRenderMistakes=renderMistakes;
renderMistakes=function(){baseRenderMistakes();qa('[data-reason-open]').forEach(el=>{el.dataset.swipeType='reason';el.dataset.swipeId=el.dataset.reasonOpen});qa('[data-set-open]').forEach(el=>{el.dataset.swipeType='set';el.dataset.swipeId=el.dataset.setOpen})};
function deleteReason(id){const r=state.reasons.find(x=>x.id===id);if(!r||!confirm('右滑删除错因「'+r.name+'」？'))return;allQuestions().filter(x=>x.reason===r.name).forEach(x=>x.reason='未分类');state.reasons=state.reasons.filter(x=>x.id!==id);save(true);renderMistakes();renderDashboard();toast('错因已删除','success')}
function deleteSet(id){const node=findNode(id);if(!node||!confirm('右滑删除题集「'+node.name+'」？'))return;const parent=findParent(id)||state.mistakes;parent.children=(parent.children||[]).filter(x=>x.id!==id);state.selectedFolderId=parent.id;save(true);renderMistakes();toast('错题集已删除','success')}
let swipeStart=null,suppressClick=false;document.addEventListener('pointerdown',e=>{const el=e.target.closest('[data-swipe-type]');if(el)swipeStart={x:e.clientX,y:e.clientY,el,type:el.dataset.swipeType,id:el.dataset.swipeId}});document.addEventListener('pointerup',e=>{if(!swipeStart)return;const dx=e.clientX-swipeStart.x,dy=Math.abs(e.clientY-swipeStart.y);if(dx>80&&dy<60){suppressClick=true;if(swipeStart.type==='reason')deleteReason(swipeStart.id);else if(swipeStart.type==='set')deleteSet(swipeStart.id)}swipeStart=null});document.addEventListener('click',e=>{if(suppressClick){e.preventDefault();e.stopImmediatePropagation();suppressClick=false}},true);
document.addEventListener('click',e=>{const add=e.target.closest('[data-add-plan-node]');if(add){openPlanNode(add.dataset.addPlanNode,add.dataset.nodeDate||state.planAnchor);return}const edit=e.target.closest('[data-plan-edit]');if(edit){const p=state.plans.find(x=>x.id===edit.dataset.planEdit);if(p)openPlanNode(p.level,p.date,p.id);return}if(e.target.closest('#savePlanNodeBtn')){savePlanNode();return}if(e.target.closest('#addMockTestBtn')){q('#mockDateInput').value=today();q('#mockScoreInput').value='';q('#mockNoteInput').value='';q('#mockTestForm').hidden=false;q('#mockScoreInput').focus();return}if(e.target.closest('#cancelMockTestBtn')){q('#mockTestForm').hidden=true;return}if(e.target.closest('#saveMockTestBtn')){const score=+q('#mockScoreInput').value,full=+q('#mockFullScoreInput').value;if(!score||!full||score>full){toast('请填写正确的分数','warn');return}state.mockTests=state.mockTests||[];state.mockTests.push({id:uid('mock'),subject:q('#mockSubjectInput').value,date:q('#mockDateInput').value||today(),score,fullScore:full,note:q('#mockNoteInput').value.trim()});state.reports=state.reports||{};delete state.reports[today()];save(true);q('#mockTestForm').hidden=true;renderDashboard();toast('模拟测试成绩已保存','success');return}if(e.target.closest('#deleteCurrentQuestionBtn')){deleteCurrentQuestion();return}if(e.target.closest('#saveCountdownBtn'))setTimeout(syncCountdownMilestones,0);if(e.target.closest('#saveWeeklyBtn'))setTimeout(()=>{syncLongTerm({level:'day',date:today(),subject:'综合'},1);renderPlan()},0)});
function deleteCurrentQuestion(){if(!state.practice)return;const p=state.practice,set=p.setData||findNode(p.setId),id=p.order[p.index],question=(set?.questions||[]).find(x=>x.id===id);if(!question||!confirm('确定删除这道错题吗？'))return;set.questions=set.questions.filter(x=>x.id!==id);state.reasons.forEach(r=>r.questionIds=r.questionIds.filter(x=>x!==id));p.order=p.order.filter(x=>x!==id);p.answers&&delete p.answers[id];if(p.setId.startsWith('reason:'))delete state.reasonSessions?.[p.setId];if(p.setId.startsWith('source:'))delete state.sourceSessions?.[p.setId];if(!p.order.length){state.practice=null;q('#practiceOverlay').classList.remove('open')}else{p.index=Math.min(p.index,p.order.length-1);syncPracticeSession();renderPractice()}save(true);renderMistakes();toast('错题已删除','success')}
document.addEventListener('click',e=>{if(e.target.closest('[data-task-toggle]')||e.target.closest('[data-plan-toggle]')||e.target.closest('[data-plan-delete]'))setTimeout(()=>{state.reports=state.reports||{};delete state.reports[today()];renderDashboard()},0)});
qa('dialog.modal').forEach(dialog=>{if(!dialog.querySelector('.dialog-exit-button'))dialog.insertAdjacentHTML('afterbegin','<button type="button" class="dialog-exit-button" data-dialog-exit>退出</button>');dialog.addEventListener('click',ev=>{if(ev.target===dialog)dialog.close()})});
document.addEventListener('click',e=>{if(e.target.closest('[data-dialog-exit]')){const d=e.target.closest('dialog');if(d)d.close()}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){const open=[...document.querySelectorAll('dialog[open]')].pop();if(open)open.close()}});const back=q('#closePracticeBtn');if(back)back.textContent='← 退出';syncCountdownMilestones();save();renderAll();setTimeout(()=>{ensureNodeDialog();renderMockTests()},0);
})();


